version: '3.9'
services:
  workspace:
    image: golang:1.17.0-alpine3.14
    restart: unless-stopped
    working_dir: /code/
    volumes:
      - ./:/code/
    command: sleep infinity

  sentry-mattermost-sidecar:
    image: itsalex/alpine-reflex:latest
    restart: unless-stopped
    environment:
      - SMS_MATTERMOST_WEBHOOK_URL=localhost:1230
    volumes:
      - ./:/code/
    ports:
      - 1323:1323
    command: reflex -g code/bin/sms -s /code/bin/sms